import {
  LayoutDashboard,
  Mail,
  Users,
  Dot,
  Workflow,
  Banknote,
  ListPlus,
  Settings,
  LogOut,
  Tag,
  BriefcaseBusiness,
  User,
  BookUser,
  Upload,
  Newspaper,
  NotebookPen,
  CreditCard,
  ClipboardList,
  SendHorizontal,
  MessageSquare,
} from "lucide-react";

const iconMapping = {
  AiOutlineAppstoreAdd: LayoutDashboard,
  MdOutlineMail: Mail,
  IoPeopleOutline: Users,
  GoDotFill: Dot,
  LuWorkflow: Workflow,
  LiaMoneyBillSolid: Banknote,
  MdFormatListBulletedAdd: ListPlus,
  FiSettings: Settings,
  MdOutlineMailOutline: Mail,
  AiOutlineLogout: LogOut,
  LiaUserTagSolid: Tag,
  IoBagAddOutline: BriefcaseBusiness,
  FaRegUser: User,
  RiContactsBook3Line: BookUser,
  AiOutlineImport: Upload,
  GrDocumentUpload: Upload,
  FaRegNewspaper: Newspaper,
  BiNotepad: NotebookPen,
  MdAddCard: CreditCard,
  MdOutlineTask: ClipboardList,
  IoPaperPlaneOutline: SendHorizontal,
  MdForum: MessageSquare,
};

export default iconMapping;
